<div class="container-fluid row row-cols-2 row-cols-lg-3 gy-3 text-start text-nowrap ">

    <button type="button" class="btn btn-light"><i class="fa-solid fa-house fa-fw"></i> fa-solid fa-house </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-magnifying-glass fa-fw"></i> fa-solid fa-magnifying-glass </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-user fa-fw"></i> fa-solid fa-user </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-user fa-fw"></i> fa-regular fa-user </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-facebook fa-fw"></i> fa-brands fa-facebook </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-check fa-fw"></i> fa-solid fa-check </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-download fa-fw"></i> fa-solid fa-download </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-twitter fa-fw"></i> fa-brands fa-twitter </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-image fa-fw"></i> fa-solid fa-image </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-image fa-fw"></i> fa-regular fa-image </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-instagram fa-fw"></i> fa-brands fa-instagram </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-phone fa-fw"></i> fa-solid fa-phone </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-tiktok fa-fw"></i> fa-brands fa-tiktok </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-bars fa-fw"></i> fa-solid fa-bars </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-envelope fa-fw"></i> fa-solid fa-envelope </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-envelope fa-fw"></i> fa-regular fa-envelope </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-linkedin fa-fw"></i> fa-brands fa-linkedin </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-star fa-fw"></i> fa-solid fa-star </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-star fa-fw"></i> fa-regular fa-star </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-location-dot fa-fw"></i> fa-solid fa-location-dot </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-github fa-fw"></i> fa-brands fa-github </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-music fa-fw"></i> fa-solid fa-music </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-wand-magic-sparkles fa-fw"></i> fa-solid fa-wand-magic-sparkles </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-heart fa-fw"></i> fa-solid fa-heart </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-heart fa-fw"></i> fa-regular fa-heart </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-arrow-right fa-fw"></i> fa-solid fa-arrow-right </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-discord fa-fw"></i> fa-brands fa-discord </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-circle-xmark fa-fw"></i> fa-solid fa-circle-xmark </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-circle-xmark fa-fw"></i> fa-regular fa-circle-xmark </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-bomb fa-fw"></i> fa-solid fa-bomb </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-poo fa-fw"></i> fa-solid fa-poo </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-camera-retro fa-fw"></i> fa-solid fa-camera-retro </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-xmark fa-fw"></i> fa-solid fa-xmark </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-youtube fa-fw"></i> fa-brands fa-youtube </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-cloud fa-fw"></i> fa-solid fa-cloud </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-comment fa-fw"></i> fa-solid fa-comment </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-comment fa-fw"></i> fa-regular fa-comment </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-caret-up fa-fw"></i> fa-solid fa-caret-up </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-truck-fast fa-fw"></i> fa-solid fa-truck-fast </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-wordpress fa-fw"></i> fa-brands fa-wordpress </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-pen-nib fa-fw"></i> fa-solid fa-pen-nib </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-arrow-up fa-fw"></i> fa-solid fa-arrow-up </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-hippo fa-fw"></i> fa-solid fa-hippo </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-face-smile fa-fw"></i> fa-solid fa-face-smile </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-face-smile fa-fw"></i> fa-regular fa-face-smile </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-calendar-days fa-fw"></i> fa-solid fa-calendar-days </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-calendar-days fa-fw"></i> fa-regular fa-calendar-days </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-paperclip fa-fw"></i> fa-solid fa-paperclip </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-slack fa-fw"></i> fa-brands fa-slack </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-shield-halved fa-fw"></i> fa-solid fa-shield-halved </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-figma fa-fw"></i> fa-brands fa-figma </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-file fa-fw"></i> fa-solid fa-file </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-file fa-fw"></i> fa-regular fa-file </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-bell fa-fw"></i> fa-solid fa-bell </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-bell fa-fw"></i> fa-regular fa-bell </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-cart-shopping fa-fw"></i> fa-solid fa-cart-shopping </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-clipboard fa-fw"></i> fa-solid fa-clipboard </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-clipboard fa-fw"></i> fa-regular fa-clipboard </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-filter fa-fw"></i> fa-solid fa-filter </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-circle-info fa-fw"></i> fa-solid fa-circle-info </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-arrow-up-from-bracket fa-fw"></i> fa-solid fa-arrow-up-from-bracket </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-bolt fa-fw"></i> fa-solid fa-bolt </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-car fa-fw"></i> fa-solid fa-car </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-ghost fa-fw"></i> fa-solid fa-ghost </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-apple fa-fw"></i> fa-brands fa-apple </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-mug-hot fa-fw"></i> fa-solid fa-mug-hot </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-circle-user fa-fw"></i> fa-solid fa-circle-user </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-circle-user fa-fw"></i> fa-regular fa-circle-user </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-pen fa-fw"></i> fa-solid fa-pen </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-google fa-fw"></i> fa-brands fa-google </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-umbrella fa-fw"></i> fa-solid fa-umbrella </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-gift fa-fw"></i> fa-solid fa-gift </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-film fa-fw"></i> fa-solid fa-film </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-stripe fa-fw"></i> fa-brands fa-stripe </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-list fa-fw"></i> fa-solid fa-list </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-gear fa-fw"></i> fa-solid fa-gear </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-algolia fa-fw"></i> fa-brands fa-algolia </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-trash fa-fw"></i> fa-solid fa-trash </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-circle-up fa-fw"></i> fa-solid fa-circle-up </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-circle-up fa-fw"></i> fa-regular fa-circle-up </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-docker fa-fw"></i> fa-brands fa-docker </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-circle-down fa-fw"></i> fa-solid fa-circle-down </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-circle-down fa-fw"></i> fa-regular fa-circle-down </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-inbox fa-fw"></i> fa-solid fa-inbox </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-rotate-right fa-fw"></i> fa-solid fa-rotate-right </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-lock fa-fw"></i> fa-solid fa-lock </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-windows fa-fw"></i> fa-brands fa-windows </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-headphones fa-fw"></i> fa-solid fa-headphones </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-barcode fa-fw"></i> fa-solid fa-barcode </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-tag fa-fw"></i> fa-solid fa-tag </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-book fa-fw"></i> fa-solid fa-book </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-bookmark fa-fw"></i> fa-solid fa-bookmark </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-bookmark fa-fw"></i> fa-regular fa-bookmark </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-paypal fa-fw"></i> fa-brands fa-paypal </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-print fa-fw"></i> fa-solid fa-print </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-camera fa-fw"></i> fa-solid fa-camera </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-stack-overflow fa-fw"></i> fa-brands fa-stack-overflow </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-font fa-fw"></i> fa-solid fa-font </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-video fa-fw"></i> fa-solid fa-video </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-circle-half-stroke fa-fw"></i> fa-solid fa-circle-half-stroke </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-droplet fa-fw"></i> fa-solid fa-droplet </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-pen-to-square fa-fw"></i> fa-solid fa-pen-to-square </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-pen-to-square fa-fw"></i> fa-regular fa-pen-to-square </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-share-from-square fa-fw"></i> fa-solid fa-share-from-square </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-share-from-square fa-fw"></i> fa-regular fa-share-from-square </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-plus fa-fw"></i> fa-solid fa-plus </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-minus fa-fw"></i> fa-solid fa-minus </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-kickstarter fa-fw"></i> fa-brands fa-kickstarter </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-share fa-fw"></i> fa-solid fa-share </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-circle-exclamation fa-fw"></i> fa-solid fa-circle-exclamation </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-fire fa-fw"></i> fa-solid fa-fire </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-eye fa-fw"></i> fa-solid fa-eye </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-eye fa-fw"></i> fa-regular fa-eye </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-eye-slash fa-fw"></i> fa-solid fa-eye-slash </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-eye-slash fa-fw"></i> fa-regular fa-eye-slash </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-dribbble fa-fw"></i> fa-brands fa-dribbble </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-plane fa-fw"></i> fa-solid fa-plane </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-magnet fa-fw"></i> fa-solid fa-magnet </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-hand fa-fw"></i> fa-solid fa-hand </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-hand fa-fw"></i> fa-regular fa-hand </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-folder fa-fw"></i> fa-solid fa-folder </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-folder fa-fw"></i> fa-regular fa-folder </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-folder-open fa-fw"></i> fa-solid fa-folder-open </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-folder-open fa-fw"></i> fa-regular fa-folder-open </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-money-bill fa-fw"></i> fa-solid fa-money-bill </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-dropbox fa-fw"></i> fa-brands fa-dropbox </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-thumbs-up fa-fw"></i> fa-solid fa-thumbs-up </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-thumbs-up fa-fw"></i> fa-regular fa-thumbs-up </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-thumbs-down fa-fw"></i> fa-solid fa-thumbs-down </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-thumbs-down fa-fw"></i> fa-regular fa-thumbs-down </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-comments fa-fw"></i> fa-solid fa-comments </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-comments fa-fw"></i> fa-regular fa-comments </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-lemon fa-fw"></i> fa-solid fa-lemon </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-lemon fa-fw"></i> fa-regular fa-lemon </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-key fa-fw"></i> fa-solid fa-key </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-thumbtack fa-fw"></i> fa-solid fa-thumbtack </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-gears fa-fw"></i> fa-solid fa-gears </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-paper-plane fa-fw"></i> fa-solid fa-paper-plane </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-paper-plane fa-fw"></i> fa-regular fa-paper-plane </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-code fa-fw"></i> fa-solid fa-code </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-squarespace fa-fw"></i> fa-brands fa-squarespace </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-globe fa-fw"></i> fa-solid fa-globe </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-truck fa-fw"></i> fa-solid fa-truck </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-city fa-fw"></i> fa-solid fa-city </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-ticket fa-fw"></i> fa-solid fa-ticket </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-tree fa-fw"></i> fa-solid fa-tree </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-wifi fa-fw"></i> fa-solid fa-wifi </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-paint-roller fa-fw"></i> fa-solid fa-paint-roller </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-bicycle fa-fw"></i> fa-solid fa-bicycle </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-android fa-fw"></i> fa-brands fa-android </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-sliders fa-fw"></i> fa-solid fa-sliders </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-brush fa-fw"></i> fa-solid fa-brush </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-hashtag fa-fw"></i> fa-solid fa-hashtag </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-flask fa-fw"></i> fa-solid fa-flask </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-briefcase fa-fw"></i> fa-solid fa-briefcase </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-compass fa-fw"></i> fa-solid fa-compass </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-compass fa-fw"></i> fa-regular fa-compass </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-dumpster-fire fa-fw"></i> fa-solid fa-dumpster-fire </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-person fa-fw"></i> fa-solid fa-person </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-person-dress fa-fw"></i> fa-solid fa-person-dress </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-shopify fa-fw"></i> fa-brands fa-shopify </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-address-book fa-fw"></i> fa-solid fa-address-book </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-address-book fa-fw"></i> fa-regular fa-address-book </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-bath fa-fw"></i> fa-solid fa-bath </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-handshake fa-fw"></i> fa-solid fa-handshake </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-handshake fa-fw"></i> fa-regular fa-handshake </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-medium fa-fw"></i> fa-brands fa-medium </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-snowflake fa-fw"></i> fa-solid fa-snowflake </button>
    <button type="button" class="btn btn-light"><i class="fa-regular fa-snowflake fa-fw"></i> fa-regular fa-snowflake </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-right-to-bracket fa-fw"></i> fa-solid fa-right-to-bracket </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-earth-americas fa-fw"></i> fa-solid fa-earth-americas </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-cloud-arrow-up fa-fw"></i> fa-solid fa-cloud-arrow-up </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-binoculars fa-fw"></i> fa-solid fa-binoculars </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-palette fa-fw"></i> fa-solid fa-palette </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-codepen fa-fw"></i> fa-brands fa-codepen </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-layer-group fa-fw"></i> fa-solid fa-layer-group </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-users fa-fw"></i> fa-solid fa-users </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-gamepad fa-fw"></i> fa-solid fa-gamepad </button>
    <button type="button" class="btn btn-light"><i class="fa-solid fa-business-time fa-fw"></i> fa-solid fa-business-time </button>
    <button type="button" class="btn btn-light"><i class="fa-brands fa-cloudflare fa-fw"></i> fa-brands fa-cloudflare </button>


</div>