<?php

//Automatically generated by zap cms
//Date:2023-12-20 14:42:25
return [
    'default' => 'default',
    'connections' => [
        'default' => [
            'driver' => 'sqlite',
            'dsn' => 'sqlite:D:/phpstudy_pro/WWW/zapcms/var/data/zapcms.db',
            'prefix' => 'zap_',
            'charset' => 'utf8',
            'collate' => 'utf8_general_ci',
        ],
    ],
];
