<?php 

//Automatically generated by zap cms
//Date:2023-12-20 18:23:55
return [
  'default' => 'default',
  'connections' => [
    'default' => [
      'driver' => 'mysql',
      'host' => 'localhost',
      'port' => '3306',
      'dbname' => 'zapcms',
      'user' => 'root',
      'password' => 'root',
      'prefix' => 'zap_',
      'charset' => 'utf8',
      'collate' => 'utf8_general_ci',
    ],
  ],
];
