<?php
/*
 * Auto-generated by: php console zapcms:UpdateBaseData -e
 * Generated at: 2026-08-10 19:15:42
 *
 * Contains base data for ALL database tables.
 * To regenerate: php console zapcms:UpdateBaseData -e
 */

namespace zapcms\support;

use zap\db\AlertTable;
use zap\db\Schema;

class CreateBaseData
{
    public static function install()
    {

        Schema::alter('admin',function (AlertTable $table){
            $table->batchInsert([
                ['id' => '1', 'username' => 'admin', 'password' => '$2y$10$owYA8LHZU.C3QxaT1XFoBeaJ8WZzHaliAxms3DQ1aLijGQN7pHpie', 'full_name' => 'admin', 'phone_number' => '', 'email' => 'zapcms-demo@zap.cn', 'avatar_url' => '', 'last_ip' => '127.0.0.1', 'last_access_time' => '1786280905', 'status' => 'activated', 'updated_at' => '1786246619', 'created_at' => '1693297157'],
            ]);
        });

        Schema::alter('admin_logs',function (AlertTable $table){
            $table->batchInsert([
                ['id' => '1', 'uid' => '1', 'username' => 'admin', 'title' => '更新个人资料', 'content' => '姓名: admin1', 'ipaddress' => '127.0.0.1', 'request_url' => 'http://zapcms.local/z-admin/user/update-profile.html', 'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36', 'request_time' => '1786246105'],
                ['id' => '2', 'uid' => '1', 'username' => 'admin', 'title' => '更新个人资料', 'content' => '姓名: admin', 'ipaddress' => '127.0.0.1', 'request_url' => 'http://zapcms.local/z-admin/user/update-profile.html', 'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36', 'request_time' => '1786246112'],
                ['id' => '3', 'uid' => '1', 'username' => 'admin', 'title' => '管理员退出', 'content' => '安全退出系统', 'ipaddress' => '127.0.0.1', 'request_url' => 'http://zapcms.local/z-admin/auth/sign-out.html', 'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36', 'request_time' => '1786246138'],
                ['id' => '4', 'uid' => '1', 'username' => 'admin', 'title' => '更新个人资料', 'content' => '姓名: admin', 'ipaddress' => '127.0.0.1', 'request_url' => 'http://zapcms.local/z-admin/user/update-profile.html', 'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36', 'request_time' => '1786246464'],
                ['id' => '5', 'uid' => '1', 'username' => 'admin', 'title' => '管理员退出', 'content' => '安全退出系统', 'ipaddress' => '127.0.0.1', 'request_url' => 'http://zapcms.local/z-admin/auth/sign-out.html', 'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36', 'request_time' => '1786246467'],
                ['id' => '6', 'uid' => '1', 'username' => 'admin', 'title' => '管理员退出', 'content' => '安全退出系统', 'ipaddress' => '127.0.0.1', 'request_url' => 'http://zapcms.local/z-admin/auth/sign-out.html', 'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36', 'request_time' => '1786246570'],
            ]);
        });

        Schema::alter('admin_menu',function (AlertTable $table){
            $table->batchInsert([
                ['id' => '1', 'title' => '内容管理', 'pid' => '0', 'path' => '1,', 'level' => '1', 'icon' => 'fa fa-cube', 'link_to' => 'Node', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(node[/.]?.*)', 'show_position' => '1', 'sort_order' => '1', 'updated_at' => '1786095171', 'created_at' => '1694683755'],
                ['id' => '2', 'title' => '栏目', 'pid' => '0', 'path' => '2,', 'level' => '1', 'icon' => 'fa fa-square-poll-horizontal', 'link_to' => 'Catalog', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(catalog[/.]?.*)', 'show_position' => '1', 'sort_order' => '2', 'updated_at' => '1786095163', 'created_at' => '1694684638'],
                ['id' => '3', 'title' => '设置', 'pid' => '0', 'path' => '3,', 'level' => '1', 'icon' => 'fa fa-gear', 'link_to' => '', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(admin-menu/.*|system/.*|user/.*)', 'show_position' => '1', 'sort_order' => '5', 'updated_at' => '1694684685', 'created_at' => '1694684685'],
                ['id' => '4', 'title' => '基础设置', 'pid' => '3', 'path' => '3,4,', 'level' => '2', 'icon' => 'fa-solid fa-angle-right', 'link_to' => 'System@settings', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(system/settings.*)', 'show_position' => '1,2', 'sort_order' => '0', 'updated_at' => '1694684704', 'created_at' => '1694684704'],
                ['id' => '5', 'title' => '系统菜单设置', 'pid' => '3', 'path' => '3,5,', 'level' => '2', 'icon' => 'fa-solid fa-angle-right', 'link_to' => 'AdminMenu', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '', 'show_position' => '1,2', 'sort_order' => '1', 'updated_at' => '1786094743', 'created_at' => '1694684714'],
                ['id' => '7', 'title' => '主题', 'pid' => '0', 'path' => '7,', 'level' => '1', 'icon' => 'fa-solid fa-wand-magic-sparkles', 'link_to' => 'Theme', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(theme[/.]?.*)', 'show_position' => '1', 'sort_order' => '3', 'updated_at' => '1786095150', 'created_at' => '1697700805'],
                ['id' => '8', 'title' => '用户管理', 'pid' => '3', 'path' => '3,8,', 'level' => '2', 'icon' => 'fa-solid fa-chevron-right', 'link_to' => 'User', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(user[/.]?.*)', 'show_position' => '1', 'sort_order' => '2', 'updated_at' => '1786095078', 'created_at' => '1697700876'],
                ['id' => '9', 'title' => '插件', 'pid' => '0', 'path' => '9,', 'level' => '1', 'icon' => 'fa-solid fa-puzzle-piece', 'link_to' => 'Plugin', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(plugin[/.]?.*)', 'show_position' => '1', 'sort_order' => '4', 'updated_at' => '1786095132', 'created_at' => '1786074715'],
                ['id' => '10', 'title' => '系统更新', 'pid' => '3', 'path' => '3,10,', 'level' => '2', 'icon' => 'fa-solid fa-arrows-rotate', 'link_to' => 'Update', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(update[/.]?.*)', 'show_position' => '1,2', 'sort_order' => '7', 'updated_at' => '1786095104', 'created_at' => '1786074715'],
                ['id' => '11', 'title' => 'Sitemap', 'pid' => '3', 'path' => '3,11,', 'level' => '2', 'icon' => 'fa-solid fa-sitemap', 'link_to' => 'System@sitemap', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(system/sitemap.*)', 'show_position' => '1,2', 'sort_order' => '4', 'updated_at' => '1786074715', 'created_at' => '1786074715'],
                ['id' => '12', 'title' => '固定链接设置', 'pid' => '3', 'path' => '3,12,', 'level' => '2', 'icon' => 'fa-solid fa-link', 'link_to' => 'System@permalink', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(system/permalink.*)', 'show_position' => '1,2', 'sort_order' => '5', 'updated_at' => '1786074715', 'created_at' => '1786074715'],
                ['id' => '13', 'title' => '代码编辑器', 'pid' => '3', 'path' => '3,13,', 'level' => '2', 'icon' => 'fa-solid fa-terminal', 'link_to' => 'Development', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(development[/.]?.*)', 'show_position' => '1,2', 'sort_order' => '8', 'updated_at' => '1786360533', 'created_at' => '1786332308'],
                ['id' => '14', 'title' => '数据库管理', 'pid' => '3', 'path' => '3,14,', 'level' => '2', 'icon' => 'fa-solid fa-database', 'link_to' => 'System@database', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(system/database|system/backup-.*)', 'show_position' => '', 'sort_order' => '6', 'updated_at' => '1786359365', 'created_at' => '1786359365'],
                ['id' => '15', 'title' => 'Slug 生成设置', 'pid' => '3', 'path' => '3,15,', 'level' => '2', 'icon' => 'fa-solid fa-language', 'link_to' => 'System@slugSettings', 'link_target' => '_self', 'link_type' => 'action', 'active_rule' => '(system/slug-settings.*)', 'show_position' => '1,2', 'sort_order' => '5.4', 'updated_at' => '1786074715', 'created_at' => '1786074715'],
            ]);
        });

        // Table `admin_meta` — no data

        Schema::alter('admin_roles',function (AlertTable $table){
            $table->batchInsert([
                ['admin_id' => '1', 'role_id' => '1', 'assignment_time' => '1698205141'],
                ['admin_id' => '1', 'role_id' => '2', 'assignment_time' => '1698496791'],
                ['admin_id' => '1', 'role_id' => '3', 'assignment_time' => '1698205141'],
                ['admin_id' => '1', 'role_id' => '5', 'assignment_time' => '1698205141'],
                ['admin_id' => '2', 'role_id' => '1', 'assignment_time' => '1698205144'],
                ['admin_id' => '2', 'role_id' => '2', 'assignment_time' => '1698205144'],
                ['admin_id' => '2', 'role_id' => '3', 'assignment_time' => '1698205144'],
                ['admin_id' => '2', 'role_id' => '5', 'assignment_time' => '1698205144'],
            ]);
        });

        Schema::alter('catalog',function (AlertTable $table){
            $table->batchInsert([
                ['id' => '28', 'slug' => 'about-us', 'title' => '公司简介', 'content' => NULL, 'pid' => '0', 'path' => '28,', 'level' => '0', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => '', 'link_type' => '', 'link_object' => '0', 'link_target' => '', 'show_position' => '1,4', 'node_type' => 'page', 'created_at' => '1698301216'],
                ['id' => '29', 'slug' => 'company-honor', 'title' => '公司荣耀', 'content' => NULL, 'pid' => '28', 'path' => '28,29,', 'level' => '1', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => '', 'link_type' => '', 'link_object' => '0', 'link_target' => '', 'show_position' => '1,2,4', 'node_type' => 'page', 'created_at' => '1698301226'],
                ['id' => '30', 'slug' => 'news', 'title' => '新闻中心', 'content' => NULL, 'pid' => '0', 'path' => '30,', 'level' => '0', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => '', 'link_type' => '', 'link_object' => '0', 'link_target' => '', 'show_position' => '1,4', 'node_type' => 'article', 'created_at' => '1698308332'],
                ['id' => '31', 'slug' => 'company', 'title' => '公司新闻', 'content' => NULL, 'pid' => '30', 'path' => '30,31,', 'level' => '1', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => '', 'link_type' => '', 'link_object' => '0', 'link_target' => '', 'show_position' => '1,4', 'node_type' => 'article', 'created_at' => '1698308345'],
                ['id' => '33', 'slug' => 'products', 'title' => '产品中心', 'content' => NULL, 'pid' => '0', 'path' => '33,', 'level' => '0', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => '', 'link_type' => '', 'link_object' => '0', 'link_target' => '', 'show_position' => '1,2,3,4', 'node_type' => 'product', 'created_at' => '1698479595'],
                ['id' => '34', 'slug' => 'phone', 'title' => '手机', 'content' => NULL, 'pid' => '33', 'path' => '33,34,', 'level' => '1', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => '', 'link_type' => '', 'link_object' => '0', 'link_target' => '', 'show_position' => '1,2,3,4', 'node_type' => 'product', 'created_at' => '1698479610'],
                ['id' => '35', 'slug' => 'computer', 'title' => '电脑', 'content' => NULL, 'pid' => '33', 'path' => '33,35,', 'level' => '1', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => NULL, 'link_type' => NULL, 'link_object' => NULL, 'link_target' => NULL, 'show_position' => '1,4', 'node_type' => 'product', 'created_at' => '1698479633'],
                ['id' => '38', 'slug' => '行业新闻', 'title' => '行业新闻', 'content' => NULL, 'pid' => '30', 'path' => '30,38,', 'level' => '1', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => NULL, 'link_type' => NULL, 'link_object' => NULL, 'link_target' => NULL, 'show_position' => '1,2,3,4', 'node_type' => 'article', 'created_at' => '1698568233'],
                ['id' => '39', 'slug' => 'history', 'title' => '发展历程', 'content' => NULL, 'pid' => '28', 'path' => '28,39,', 'level' => '1', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => '', 'link_type' => '', 'link_object' => '0', 'link_target' => '', 'show_position' => '1,4', 'node_type' => 'page', 'created_at' => '1698572057'],
                ['id' => '40', 'slug' => 'contact', 'title' => '联系我们', 'content' => NULL, 'pid' => '28', 'path' => '28,40,', 'level' => '1', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => '0', 'link_type' => '', 'link_object' => NULL, 'link_target' => '', 'show_position' => '1,2,3,4', 'node_type' => 'page', 'created_at' => '1698572075'],
                ['id' => '41', 'slug' => '--zap-link-url', 'title' => '联系我们', 'content' => 'page', 'pid' => '0', 'path' => '41,', 'level' => '0', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => 'contact', 'link_type' => 'catalog', 'link_object' => '40', 'link_target' => '_self', 'show_position' => '1,2,3', 'node_type' => 'link-url', 'created_at' => '1698573297'],
                ['id' => '46', 'slug' => 'faq', 'title' => '常见问题', 'content' => NULL, 'pid' => '0', 'path' => '46,', 'level' => '0', 'sort_order' => '0', 'icon' => NULL, 'thumb_url' => NULL, 'link_to' => '', 'link_type' => '', 'link_object' => '0', 'link_target' => '', 'show_position' => '1', 'node_type' => 'faq', 'created_at' => '1698723044'],
            ]);
        });

        // Table `comments` — no data

        Schema::alter('node',function (AlertTable $table){
            $table->batchInsert([
                ['id' => '28', 'author_id' => '1', 'node_type' => 'catalog', 'title' => '公司简介', 'slug' => 'about-us', 'excerpt' => '', 'content' => '<div><img src="/storage/images/02522a2b2726fb0a03bb19f2d8d9524d.jpg" style="width:422.667px;float:left;height:327.99px;" class="note-float-left" alt="02522a2b2726fb0a03bb19f2d8d9524d.jpg" /><span>作为一家专业从事软件开发、SSL证书申请以及网站建设的公司，嘉兴领格信息技术有限公司以其专业的技术实力和丰富的经验，为客户提供优质的一站式服务。在当今数字化时代，软件开发和网站建设已经成为企业必不可少的一部分。而SSL证书的申请和应用也变得愈发重要，为保障用户数据安全和网络安全提供了有力支持。嘉兴领格信息技术有限公司正是在这一背景下应运而生，致力于为客户解决各种软件开发、SSL证书申请和网站建设的难题。首先，让我们来看看嘉兴领格信息技术有限公司的专业软件开发能力。公司拥有一支高素质的开发团队，他们具备丰富的编程经验和深厚的技术功底。无论是定制化的软件项目还是标准化的软件解决方案，嘉兴领格信息技术有限公司都能提供最佳的解决方案。他们深入了解客户的需求，并根据不同行业的特点，为其量身定制适合的软件产品。通过持续的技术创新和严格的质量控制，嘉兴领格信息技术有限公司的软件产品在市场上赢得了良好的口碑。其次，嘉兴领格信息技术有限公司在SSL证书申请方面也有着丰富的经验。随着网络攻击的不断增加，保护用户数据安全的重要性日益凸显。SSL证书作为一种加密传输协议，能够有效防止用户数据的泄露和篡改。嘉兴领格信息技术有限公司为客户提供全方位的SSL证书申请服务，从证书的申请到安装配置，全程为客户保驾护航。他们与多家知名的SSL证书颁发机构建立了良好的合作关系，确保客户能够获得最权威、最可靠的SSL证书。</span></div><div><br /></div><div>最后，让我们来了解一下嘉兴领格信息技术有限公司的网站建设能力。作为一个专业的网站建设公司，嘉兴领格信息技术有限公司拥有一支富有创造力和执行力的团队。他们能够为客户提供高质量、创新性的网站设计和开发服务。无论是企业官网、电子商务平台还是社交媒体网站，嘉兴领格信息技术有限公司都能够提供一站式解决方案。他们的设计团队注重用户体验和界面美观性，同时结合搜索引擎优化（SEO）的原则，使客户的网站能够在搜索结果中排名更靠前。</div><div><br /></div>', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'page', 'status' => 'publish', 'pub_time' => '1698478986', 'update_time' => '1702522239', 'add_time' => '1698478986'],
                ['id' => '29', 'author_id' => '1', 'node_type' => 'catalog', 'title' => '公司荣耀', 'slug' => 'company-honor', 'excerpt' => '', 'content' => '<p>作为一家专业的软件开发、SSL证书与网站建设公司，嘉兴领格信息技术有限公司以其卓越的技术实力和丰富的经验，赢得了客户的信任和赞誉。</p><p><br></p><p>专业团队：我们拥有一支高素质的开发团队，他们具备丰富的编程经验和深厚的技术功底。团队成员经过严格的选拔和培训，能够为客户提供最优质的软件开发、SSL证书申请和网站建设服务。</p><p><br></p><p>定制化解决方案：我们深入了解客户的需求，并根据不同行业的特点，为其量身定制适合的软件产品和网站设计方案。通过持续的技术创新和严格的质量控制，我们的产品和服务在市场上赢得了良好的口碑。</p><p><br></p><p>优质客户服务：我们始终将客户的利益放在首位，致力于为客户提供全方位、个性化的服务。无论是在软件开发、SSL证书申请还是网站建设过程中，我们都与客户保持密切的沟通，确保项目的顺利进行和客户的满意度。</p><p><br></p><p>合作伙伴关系：我们与多家知名的软件开发公司、SSL证书颁发机构以及网络服务提供商建立了长期稳定的合作伙伴关系。这些合作关系使我们能够为客户提供更全面、更高效的服务。</p><p><br></p><p>客户案例：我们为众多知名企业提供了软件开发、SSL证书申请和网站建设服务，并取得了显著的成果。这些成功案例充分证明了我们在行业内的专业能力和市场竞争力。</p><p><br></p><p>社会责任：我们积极履行企业社会责任，关注环境保护和社会公益事业。我们致力于通过技术创新和优质服务，为客户创造更大的价值，为社会做出贡献。</p><p><br></p><p><br></p>', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'page', 'status' => 'publish', 'pub_time' => '1698478986', 'update_time' => '1702521147', 'add_time' => '1698478986'],
                ['id' => '30', 'author_id' => '0', 'node_type' => 'catalog', 'title' => '新闻中心', 'slug' => 'news', 'excerpt' => '', 'content' => '', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'article', 'status' => 'publish', 'pub_time' => '1698478986', 'update_time' => '1698645355', 'add_time' => '1698478986'],
                ['id' => '31', 'author_id' => '0', 'node_type' => 'catalog', 'title' => '公司新闻', 'slug' => 'company', 'excerpt' => '', 'content' => '', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'article', 'status' => 'publish', 'pub_time' => '1698478986', 'update_time' => '1698645358', 'add_time' => '1698478986'],
                ['id' => '32', 'author_id' => '1', 'node_type' => 'article', 'title' => '消息称vivo X100系列手机将搭载行业唯一APO长焦', 'slug' => '新闻测试', 'excerpt' => '', 'content' => '<p>IT之家 10 月 30 日消息，供应链消息透露，即将发布的 vivo X100 系列将全系搭载潜望长焦镜头，并带来行业唯一获得蔡司 APO 标准认证的浮动长焦摄像头。据悉，APO 标准通常用于评价专业光学影像器材的色差控制水平，通过认证的镜头都拥有顶级的颜色校正能力。</p><p>此外，vivo X100 系列还将全系实现长焦微距功能。rn根据此前消息，vivo X100 系列还有多个首发技术，包括首发搭载海力士 LPDDR5T 内存，相比主流 LPDDR5X 内存，LPDDR5T 的读取速度提升达 13%，是目前行业最快的移动 DRAM。此外，新机还将首发搭载联发科天玑 9300 处理器和 vivo 6nm 自研影像芯片 V3。</p>', 'keywords' => '', 'description' => '', 'image' => '/storage/images/84d9ee44e457ddef7f2c4f25dc8fa865.jpg', 'hits' => '124', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => '', 'status' => 'publish', 'pub_time' => '1698308815', 'update_time' => '1702520217', 'add_time' => '1698308820'],
                ['id' => '33', 'author_id' => '0', 'node_type' => 'catalog', 'title' => '产品中心', 'slug' => 'products', 'excerpt' => '', 'content' => '', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'product', 'status' => 'publish', 'pub_time' => '1698479595', 'update_time' => '1698645255', 'add_time' => '1698479595'],
                ['id' => '34', 'author_id' => '0', 'node_type' => 'catalog', 'title' => '手机', 'slug' => 'phone', 'excerpt' => '', 'content' => '', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'product', 'status' => 'publish', 'pub_time' => '1698479610', 'update_time' => '1698645259', 'add_time' => '1698479610'],
                ['id' => '35', 'author_id' => '0', 'node_type' => 'catalog', 'title' => '电脑', 'slug' => 'computer', 'excerpt' => '', 'content' => '', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'product', 'status' => 'publish', 'pub_time' => '1698479633', 'update_time' => '1698479633', 'add_time' => '1698479633'],
                ['id' => '36', 'author_id' => '1', 'node_type' => 'product', 'title' => 'iPhone 15', 'slug' => 'iphone-15', 'excerpt' => '', 'content' => '<p>iPhone 15</p><p>iPhone 15</p><p>iPhone 15</p><p>iPhone 15</p><p>iPhone 15<br></p>', 'keywords' => '', 'description' => '', 'image' => '/storage/images/84d9ee44e457ddef7f2c4f25dc8fa865.jpg', 'hits' => '23', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => '', 'status' => 'publish', 'pub_time' => '1698495012', 'update_time' => '1699519805', 'add_time' => '1698495036'],
                ['id' => '37', 'author_id' => '1', 'node_type' => 'product', 'title' => 'Macbook Pro 15', 'slug' => 'macbook-pro-15', 'excerpt' => '', 'content' => '<p>Macbook Pro 15</p><p>Macbook Pro 15</p><p>Macbook Pro 15</p><p>Macbook Pro 15</p><p>Macbook Pro 15<img style="width: 800px;" src="/storage/images/3644a684f98ea8fe223c713b77189a77.jpg"><br></p>', 'keywords' => '', 'description' => '', 'image' => '/storage/images/7ef605fc8dba5425d6965fbd4c8fbe1f.jpg', 'hits' => '34', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => '', 'status' => 'publish', 'pub_time' => '1698495259', 'update_time' => '1699845643', 'add_time' => '1698495272'],
                ['id' => '38', 'author_id' => '0', 'node_type' => 'catalog', 'title' => '行业新闻', 'slug' => '行业新闻', 'excerpt' => '', 'content' => '', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'article', 'status' => 'publish', 'pub_time' => '1698568233', 'update_time' => '1698568233', 'add_time' => '1698568233'],
                ['id' => '39', 'author_id' => '1', 'node_type' => 'catalog', 'title' => '发展历程', 'slug' => 'history', 'excerpt' => '', 'content' => '<p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p><p>发展历程</p>', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'page', 'status' => 'publish', 'pub_time' => '1698572057', 'update_time' => '1699614981', 'add_time' => '1698572057'],
                ['id' => '40', 'author_id' => '1', 'node_type' => 'catalog', 'title' => '联系我们', 'slug' => 'contact', 'excerpt' => '', 'content' => '<p>如果您有任何关于软件开发、SSL证书申请或网站建设的需求，欢迎随时联系我们。</p><p><br></p><p>以下是我们的联系方式：</p><p>电话：+86 1234567890</p><p>邮箱：info@jiaxinglingge.com</p><p>地址：中国浙江省嘉兴市南湖区XX街道XX号</p><p>官方网站：https://www.jiaxinglingge.com/</p><p><br></p><p>您可以通过电话、电子邮件或访问我们的官方网站与我们取得联系。我们的专业团队将竭诚为您提供最优质的服务和解决方案。期待与您的合作！</p><p><br></p><p><br></p><p><br></p><p><br></p>', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'page', 'status' => 'publish', 'pub_time' => '1698572075', 'update_time' => '1702521103', 'add_time' => '1698572075'],
                ['id' => '41', 'author_id' => '0', 'node_type' => 'catalog', 'title' => '联系我们', 'slug' => '--zap-link-url', 'excerpt' => '', 'content' => '', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'link-url', 'status' => 'publish', 'pub_time' => '1698573297', 'update_time' => '1699621050', 'add_time' => '1698573297'],
                ['id' => '42', 'author_id' => '1', 'node_type' => 'article', 'title' => '华为申请“遥遥领先”商标！新品发布会曾被“遥遥领先”刷屏', 'slug' => '华为申请遥遥领先商标新品发布会曾被遥遥领先刷屏', 'excerpt' => '', 'content' => '<div>近期，因华为Mate60系列手机发售，“遥遥领先”成为网络热词。</div><div>据企查查数据显示，近日，华为技术有限公司申请注册“遥遥领先”商标，国际分类为运输工具、科学仪器，当前商标状态为等待实质审查。</div><div>近期，因华为Mate60系列手机发售，“遥遥领先”成为网络热词。</div><div>据企查查数据显示，近日，华为技术有限公司申请注册“遥遥领先”商标，国际分类为运输工具、科学仪器，当前商标状态为等待实质审查。</div><div><br></div>', 'keywords' => '', 'description' => '', 'image' => '/storage/images/02522a2b2726fb0a03bb19f2d8d9524d.jpg', 'hits' => '27', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => '', 'status' => 'publish', 'pub_time' => '1698650814', 'update_time' => '1702455212', 'add_time' => '1698650832'],
                ['id' => '43', 'author_id' => '1', 'node_type' => 'product', 'title' => 'iPhone 14 Pro MAX', 'slug' => 'iphone-14-pro-max', 'excerpt' => '', 'content' => '<p>iPhone 14 Pro MAX</p><p>iPhone 14 Pro MAX</p><hr><p>iPhone 14 Pro MAX</p><p>iPhone 14 Pro MAX</p><p>iPhone 14 Pro MAX</p><p>iPhone 14 Pro MAX</p><p>iPhone 14 Pro MAXiPhone 14 Pro MAX</p><hr><p><br></p><hr><p>iPhone 14 Pro MAX</p><hr><p>iPhone 14 Pro MAX</p><hr><p>iPhone 14 Pro MAX<br></p>', 'keywords' => '', 'description' => '', 'image' => '/storage/images/7ef605fc8dba5425d6965fbd4c8fbe1f.jpg', 'hits' => '3', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => '', 'status' => 'publish', 'pub_time' => '1698653114', 'update_time' => '1699622837', 'add_time' => '1698653137'],
                ['id' => '44', 'author_id' => '1', 'node_type' => 'product', 'title' => 'HUAWEI MateBook', 'slug' => 'huawei-matebook', 'excerpt' => '', 'content' => '<p>HUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBookHUAWEI MateBook<br></p>', 'keywords' => '', 'description' => '', 'image' => '/storage/images/013d407166ec4fa56eb1e1f8cbe183b9.jpg', 'hits' => '4', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => '', 'status' => 'publish', 'pub_time' => '1698653141', 'update_time' => '1699845753', 'add_time' => '1698653159'],
                ['id' => '45', 'author_id' => '1', 'node_type' => 'product', 'title' => '这是一篇中文产品测试超长标题', 'slug' => '这是一篇中文产品测试超长标题', 'excerpt' => '', 'content' => '<p>这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题这是一篇中文产品测试超长标题<br></p>', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '29', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => '', 'status' => 'publish', 'pub_time' => '1698718369', 'update_time' => '1698718387', 'add_time' => '1698718387'],
                ['id' => '46', 'author_id' => '0', 'node_type' => 'catalog', 'title' => '常见问题', 'slug' => 'faq', 'excerpt' => '', 'content' => '', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => 'faq', 'status' => 'publish', 'pub_time' => '1698723044', 'update_time' => '1702455386', 'add_time' => '1698723044'],
                ['id' => '47', 'author_id' => '1', 'node_type' => 'faq', 'title' => 'Zap CMS 的系统要求', 'slug' => 'zapcms-的系统要求', 'excerpt' => '', 'content' => '<p>ZapCMS 需要以下服务器配置才能运行：</p><p><br /></p><p>需求配置</p><p>Web服务器Apache Web server 2.4或任何更高版本。（Apache Web Server 2.2 在2018年已经停止维护，因此不建议使用它）。</p><p>PHP我们推荐使用PHP 7.4+。</p><p>MySQL最低版本为5.6，建议使用最新版本。</p><p>服务器RAM越多越好。我们建议将每个脚本的内存分配（memory_limit）设置为至少128M+。</p><p><span>ZapCMS</span>可以运行在大多数操作系统，Linux （CentOS、Debian、Ubuntu）、Unix（FreeBSD、MacOS）、Windows</p>', 'keywords' => '', 'description' => '', 'image' => '/storage/d1f491a404d6854880943e5c3cd9ca25.jpg', 'hits' => '5', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => '', 'status' => 'publish', 'pub_time' => '1698731746', 'update_time' => '1702522094', 'add_time' => '1698732845'],
                ['id' => '48', 'author_id' => '1', 'node_type' => 'faq', 'title' => 'Zap CMS 可以用于商业网站吗？', 'slug' => 'zapcms-可以用于商业网站吗', 'excerpt' => '', 'content' => '<p>您可以用ZAPCMS搭建任何站点，未获得商业授权的客户，必须保留网站底部 【Powered by ZapCMS】 版权标识。rn</p><p>rn禁止使用ZAPCMS搭建任何违法国家法律法规的站点，已经发现立即举报至相关部门。</p>', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => '', 'status' => 'publish', 'pub_time' => '1698733712', 'update_time' => '1702521319', 'add_time' => '1698733978'],
                ['id' => '49', 'author_id' => '1', 'node_type' => 'faq', 'title' => '支持什么数据库?', 'slug' => '支持什么数据库', 'excerpt' => '', 'content' => '<p>推荐使用MySQL、MariaDB</p><p>SQLite3、PostgreSQL还未完全适配。</p>', 'keywords' => '', 'description' => '', 'image' => '', 'hits' => '0', 'sort_order' => '0', 'comment_status' => '', 'comment_count' => '0', 'mime_type' => '', 'status' => 'publish', 'pub_time' => '1698734821', 'update_time' => '1699613196', 'add_time' => '1698734905'],
            ]);
        });

        // Table `node_meta` — no data

        Schema::alter('node_relation',function (AlertTable $table){
            $table->batchInsert([
                ['catalog_id' => '28', 'node_id' => '28', 'level' => '0'],
                ['catalog_id' => '29', 'node_id' => '29', 'level' => '1'],
                ['catalog_id' => '30', 'node_id' => '32', 'level' => '0'],
                ['catalog_id' => '30', 'node_id' => '42', 'level' => '0'],
                ['catalog_id' => '31', 'node_id' => '32', 'level' => '1'],
                ['catalog_id' => '33', 'node_id' => '36', 'level' => '0'],
                ['catalog_id' => '33', 'node_id' => '37', 'level' => '0'],
                ['catalog_id' => '33', 'node_id' => '43', 'level' => '0'],
                ['catalog_id' => '33', 'node_id' => '44', 'level' => '0'],
                ['catalog_id' => '33', 'node_id' => '45', 'level' => '0'],
                ['catalog_id' => '34', 'node_id' => '36', 'level' => '1'],
                ['catalog_id' => '34', 'node_id' => '43', 'level' => '1'],
                ['catalog_id' => '34', 'node_id' => '45', 'level' => '1'],
                ['catalog_id' => '35', 'node_id' => '37', 'level' => '1'],
                ['catalog_id' => '35', 'node_id' => '44', 'level' => '1'],
                ['catalog_id' => '38', 'node_id' => '42', 'level' => '1'],
                ['catalog_id' => '39', 'node_id' => '39', 'level' => '1'],
                ['catalog_id' => '40', 'node_id' => '40', 'level' => '1'],
                ['catalog_id' => '46', 'node_id' => '47', 'level' => '0'],
                ['catalog_id' => '46', 'node_id' => '48', 'level' => '0'],
                ['catalog_id' => '46', 'node_id' => '49', 'level' => '0'],
            ]);
        });

        // Table `node_type_field` — no data

        Schema::alter('node_types',function (AlertTable $table){
            $table->batchInsert([
                ['type_id' => '1', 'type_name' => 'article', 'title' => '文章', 'description' => '文章、新闻', 'node_type' => 'zap\\node\\AbstractNodeType', 'version' => '1.0.0', 'sort_order' => '0', 'status' => '1', 'updated_at' => '1694153650', 'created_at' => '1694153650'],
                ['type_id' => '2', 'type_name' => 'product', 'title' => '产品', 'description' => '简单企业产品展示', 'node_type' => 'zap\\node\\AbstractNodeType', 'version' => '1.0.0', 'sort_order' => '0', 'status' => '1', 'updated_at' => '1694153650', 'created_at' => '1694153650'],
                ['type_id' => '3', 'type_name' => 'page', 'title' => '单页', 'description' => '单页', 'node_type' => 'zap\\node\\AbstractNodeType', 'version' => '1.0.0', 'sort_order' => '0', 'status' => '1', 'updated_at' => '1694153650', 'created_at' => '1694153650'],
                ['type_id' => '4', 'type_name' => 'faq', 'title' => 'FAQ', 'description' => '常见问题', 'node_type' => 'zap\\node\\AbstractNodeType', 'version' => '1.0.0', 'sort_order' => '0', 'status' => '1', 'updated_at' => '1694153650', 'created_at' => '1694153650'],
                ['type_id' => '5', 'type_name' => 'link-url', 'title' => '链接', 'description' => '链接地址', 'node_type' => 'zap\\node\\AbstractNodeType', 'version' => '1.0.0', 'sort_order' => '0', 'status' => '1', 'updated_at' => '1694153650', 'created_at' => '1694153650'],
            ]);
        });

        Schema::alter('options',function (AlertTable $table){
            $table->batchInsert([
                ['id' => '11', 'option_name' => 'website.title', 'option_value' => 'ZapCMS', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '12', 'option_name' => 'website.slogan', 'option_value' => 'OpenSource CMS', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '13', 'option_name' => 'website.keywords', 'option_value' => 'ZapCMS,ZAP,CMS,PHP OpenSource CMS', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '14', 'option_name' => 'website.description', 'option_value' => '', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '15', 'option_name' => 'website.icp', 'option_value' => '浙ICP备0000000000号', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '16', 'option_name' => 'website.copyright', 'option_value' => 'ZAPCMS 版权所有', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '17', 'option_name' => 'website.address', 'option_value' => '公司详细地址', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '18', 'option_name' => 'website.tel', 'option_value' => '057388888888', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '19', 'option_name' => 'website.head_script', 'option_value' => '', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '20', 'option_name' => 'website.foot_script', 'option_value' => '', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '21', 'option_name' => 'website.theme', 'option_value' => 'basic', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '22', 'option_name' => 'website.route', 'option_value' => '0', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '23', 'option_name' => 'website.route_rule', 'option_value' => '', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '24', 'option_name' => 'website.email', 'option_value' => 'admin@zapcms.local', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '33', 'option_name' => 'cache.ttl', 'option_value' => '10000', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '50', 'option_name' => 'zap_cms.install_date', 'option_value' => '1786074715', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '60', 'option_name' => 'mail.engine', 'option_value' => 'mail', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '61', 'option_name' => 'mail.host', 'option_value' => 'localhost', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '62', 'option_name' => 'mail.username', 'option_value' => '', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '63', 'option_name' => 'mail.password', 'option_value' => '', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '64', 'option_name' => 'mail.port', 'option_value' => '25', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '65', 'option_name' => 'mail.timeout', 'option_value' => '5', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '80', 'option_name' => 'permalink.structure', 'option_value' => '/%postname%/', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '81', 'option_name' => 'permalink.catalog_prefix', 'option_value' => 'catalog', 'sort_order' => '0', 'autoload' => '1'],
                ['id' => '1034', 'option_name' => 'basic_home.slide', 'option_value' => '[{"img_path":"/themes/basic/img/banner1.png","link":"https://zap.cn"},{"img_path":"/themes/basic/img/banner2.png","link":"https://zap.cn"}]', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1036', 'option_name' => 'basic_home.service_title', 'option_value' => '服务项目', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1037', 'option_name' => 'basic_home.service_subtitle', 'option_value' => 'SERVICES', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1038', 'option_name' => 'basic_home.service1_title', 'option_value' => '软件开发与定制服务', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1039', 'option_name' => 'basic_home.service1_content', 'option_value' => '根据客户的具体需求进行软件设计和开发，以满足客户的个性化需求。', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1040', 'option_name' => 'basic_home.service1_icon', 'option_value' => 'fa fa-code', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1041', 'option_name' => 'basic_home.service2_title', 'option_value' => '移动应用开发', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1042', 'option_name' => 'basic_home.service2_content', 'option_value' => '提供移动应用开发服务，帮助他们将业务拓展到移动设备上。无论是为iOS、Android还是跨平台开发，软件公司都能够提供专业的技术支持和解决方案。', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1043', 'option_name' => 'basic_home.service2_icon', 'option_value' => 'fa fa-cubes', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1044', 'option_name' => 'basic_home.service3_title', 'option_value' => '网站设计与开发', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1045', 'option_name' => 'basic_home.service3_content', 'option_value' => '网站是企业展示形象、传递信息的重要渠道。软件公司为客户提供网站设计与开发服务，帮助他们建立专业、易用的网站。从网站的规划、设计到开发和测试，软件公司都能够提供全方位的支持，确保网站能够满足客户的需求并具有良好的用户体验。', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1046', 'option_name' => 'basic_home.service3_icon', 'option_value' => 'fa fa-television', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1047', 'option_name' => 'basic_home.service4_title', 'option_value' => '云计算与数据管理', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1048', 'option_name' => 'basic_home.service4_content', 'option_value' => '随着数据量的不断增长，数据管理和存储成为了一个重要的问题。软件公司提供云计算和数据管理服务，帮助客户有效地管理和分析数据。通过使用云计算技术，客户可以将数据存储在云端，实现数据的高效管理和共享。同时，软件公司还提供数据分析和挖掘服务，帮助客户从数据中获取有价值的信息和洞察。', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1049', 'option_name' => 'basic_home.service4_icon', 'option_value' => 'fa fa-cloud', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1050', 'option_name' => 'basic_home.service5_title', 'option_value' => '人工智能与机器学习', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1051', 'option_name' => 'basic_home.service5_content', 'option_value' => '人工智能和机器学习是当前科技领域的热门话题。软件公司利用先进的技术和算法，为客户提供人工智能和机器学习解决方案。这些解决方案可以帮助客户实现自动化、智能化的业务处理，提高工作效率和准确性。无论是自然语言处理、图像识别还是智能推荐系统，软件公司都能够提供专业的技术支持和解决方案。', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1052', 'option_name' => 'basic_home.service5_icon', 'option_value' => 'fa fa-graduation-cap', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1053', 'option_name' => 'basic_home.service6_title', 'option_value' => '安全与隐私保护', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1054', 'option_name' => 'basic_home.service6_content', 'option_value' => '随着网络攻击和数据泄露事件的不断增多，安全与隐私保护成为了一个紧迫的问题。软件公司提供安全与隐私保护服务，帮助客户保护其数据和系统的安全。通过使用先进的安全技术和策略，软件公司可以有效地防止黑客攻击和数据泄露，确保客户的数据和系统的安全性。', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1055', 'option_name' => 'basic_home.service6_icon', 'option_value' => 'fa fa-diamond', 'sort_order' => '0', 'autoload' => '0'],
                ['id' => '1056', 'option_name' => 'basic_home.about_us', 'option_value' => '<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; outline: none; padding: 0px; line-height: 26px; word-break: break-word;"><img src="http://zapcms.local/themes/basic/img/aboutus.png" class="note-float-right" style="float: right;"><span >&nbsp; &nbsp; &nbsp; &nbsp;作为一家专业从事软件开发、SSL证书申请以及网站建设的公司，嘉兴领格信息技术有限公司以其专业的技术实力和丰富的经验，为客户提供优质的一站式服务。在当今数字化时代，软件开发和网站建设已经成为企业必不可少的一部分。而SSL证书的申请和应用也变得愈发重要，为保障用户数据安全和网络安全提供了有力支持。嘉兴领格信息技术有限公司正是在这一背景下应运而生，致力于为客户解决各种软件开发、SSL证书申请和网站建设的难题。</span><span >首先，让我们来看看嘉兴领格信息技术有限公司的专业软件开发能力。公司拥有一支高素质的开发团队，他们具备丰富的编程经验和深厚的技术功底。无论是定制化的软件项目还是标准化的软件解决方案，嘉兴领格信息技术有限公司都能提供最佳的解决方案。他们深入了解客户的需求，并根据不同行业的特点，为其量身定制适合的软件产品。通过持续的技术创新和严格的质量控制，嘉兴领格信息技术有限公司的软件产品在市场上赢得了良好的口碑。</span><span >其次，嘉兴领格信息技术有限公司在SSL证书申请方面也有着丰富的经验。随着网络攻击的不断增加，保护用户数据安全的重要性日益凸显。SSL证书作为一种加密传输协议，能够有效防止用户数据的泄露和篡改。嘉兴领格信息技术有限公司为客户提供全方位的SSL证书申请服务，从证书的申请到安装配置，全程为客户保驾护航。他们与多家知名的SSL证书颁发机构建立了良好的合作关系，确保客户能够获得最权威、最可靠的SSL证书。<br></span></p><p ><span >&nbsp; &nbsp; &nbsp; &nbsp;最后，让我们来了解一下嘉兴领格信息技术有限公司的网站建设能力。作为一个专业的网站建设公司，嘉兴领格信息技术有限公司拥有一支富有创造力和执行力的团队。他们能够为客户提供高质量、创新性的网站设计和开发服务。无论是企业官网、电子商务平台还是社交媒体网站，嘉兴领格信息技术有限公司都能够提供一站式解决方案。他们的设计团队注重用户体验和界面美观性，同时结合搜索引擎优化（SEO）的原则，使客户的网站能够在搜索结果中排名更靠前。</span></p>', 'sort_order' => '0', 'autoload' => '0'],
            ]);
        });

        Schema::alter('permissions',function (AlertTable $table){
            $table->batchInsert([
                ['perm_id' => '7', 'title' => '用户管理', 'pid' => '0', 'path' => '7,', 'level' => '0', 'perm_key' => 'user', 'extras' => '{\\"modify\\":\\"修改\\",\\"access\\":\\"访问\\"}', 'description' => '', 'updated_at' => '1698204898', 'created_at' => '1698204409'],
            ]);
        });

        Schema::alter('permissions_path',function (AlertTable $table){
            $table->batchInsert([
                ['perm_id' => '7', 'path_id' => '7', 'level' => '0'],
            ]);
        });

        // Table `plugin` — no data

        Schema::alter('roles',function (AlertTable $table){
            $table->batchInsert([
                ['role_id' => '1', 'name' => '超级管理员', 'description' => '系统管理员', 'status' => '1', 'updated_at' => '1698571937', 'created_at' => '1697774895'],
                ['role_id' => '2', 'name' => '编辑', 'description' => '发布文章', 'status' => '1', 'updated_at' => '1698571949', 'created_at' => '1698110905'],
                ['role_id' => '3', 'name' => '内容管理员', 'description' => '内容编辑', 'status' => '1', 'updated_at' => '1698571944', 'created_at' => '1698110928'],
                ['role_id' => '5', 'name' => '发布者', 'description' => '发布文章', 'status' => '1', 'updated_at' => '1698205114', 'created_at' => '1698205114'],
            ]);
        });

        Schema::alter('roles_permissions',function (AlertTable $table){
            $table->batchInsert([
                ['role_id' => '1', 'perm_key' => 'admin_menu_1', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'admin_menu_2', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'admin_menu_3', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'admin_menu_4', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'admin_menu_5', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'admin_menu_7', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'admin_menu_8', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'admin_menu_9', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'admin_menu_10', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'admin_menu_11', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'admin_menu_12', 'extras' => '', 'assignment_time' => '1698571937'],
                ['role_id' => '1', 'perm_key' => 'user', 'extras' => 'modify,access', 'assignment_time' => '1698571937'],
                ['role_id' => '2', 'perm_key' => 'admin_menu_1', 'extras' => '', 'assignment_time' => '1698571949'],
                ['role_id' => '2', 'perm_key' => 'admin_menu_2', 'extras' => '', 'assignment_time' => '1698571949'],
                ['role_id' => '2', 'perm_key' => 'admin_menu_3', 'extras' => '', 'assignment_time' => '1698571949'],
                ['role_id' => '2', 'perm_key' => 'admin_menu_4', 'extras' => '', 'assignment_time' => '1698571949'],
                ['role_id' => '2', 'perm_key' => 'admin_menu_5', 'extras' => '', 'assignment_time' => '1698571949'],
                ['role_id' => '2', 'perm_key' => 'admin_menu_7', 'extras' => '', 'assignment_time' => '1698571949'],
                ['role_id' => '2', 'perm_key' => 'admin_menu_8', 'extras' => '', 'assignment_time' => '1698571949'],
                ['role_id' => '2', 'perm_key' => 'user', 'extras' => '', 'assignment_time' => '1698571949'],
                ['role_id' => '3', 'perm_key' => 'admin_menu_1', 'extras' => '', 'assignment_time' => '1698571945'],
                ['role_id' => '3', 'perm_key' => 'admin_menu_2', 'extras' => '', 'assignment_time' => '1698571945'],
                ['role_id' => '3', 'perm_key' => 'admin_menu_3', 'extras' => '', 'assignment_time' => '1698571945'],
                ['role_id' => '3', 'perm_key' => 'admin_menu_4', 'extras' => '', 'assignment_time' => '1698571945'],
                ['role_id' => '3', 'perm_key' => 'admin_menu_5', 'extras' => '', 'assignment_time' => '1698571945'],
                ['role_id' => '3', 'perm_key' => 'admin_menu_7', 'extras' => '', 'assignment_time' => '1698571945'],
                ['role_id' => '3', 'perm_key' => 'admin_menu_8', 'extras' => '', 'assignment_time' => '1698571945'],
                ['role_id' => '3', 'perm_key' => 'user', 'extras' => '', 'assignment_time' => '1698571945'],
                ['role_id' => '5', 'perm_key' => 'admin_menu_1', 'extras' => '', 'assignment_time' => '1698205114'],
                ['role_id' => '5', 'perm_key' => 'admin_menu_2', 'extras' => '', 'assignment_time' => '1698205114'],
                ['role_id' => '5', 'perm_key' => 'admin_menu_3', 'extras' => '', 'assignment_time' => '1698205114'],
                ['role_id' => '5', 'perm_key' => 'admin_menu_4', 'extras' => '', 'assignment_time' => '1698205114'],
                ['role_id' => '5', 'perm_key' => 'admin_menu_5', 'extras' => '', 'assignment_time' => '1698205114'],
                ['role_id' => '5', 'perm_key' => 'admin_menu_7', 'extras' => '', 'assignment_time' => '1698205114'],
                ['role_id' => '5', 'perm_key' => 'admin_menu_8', 'extras' => '', 'assignment_time' => '1698205114'],
                ['role_id' => '5', 'perm_key' => 'user', 'extras' => 'modify,access', 'assignment_time' => '1698205114'],
            ]);
        });

        // Table `tags` — no data

        // Table `update_history` — no data
    }
}
