<?php
/*
 * Auto-generated by: php console zapcms:UpdateBaseData -e
 * Generated at: 2026-08-11 21:05:52
 *
 * Table structure for ALL database tables.
 * To regenerate: php console zapcms:UpdateBaseData -e
 */

namespace zapcms\support;

use zap\db\Schema;
use zap\db\TableSchema;

class CreateTables
{
    public function createSchema()
    {

        Schema::dropIfExists('admin');
        Schema::create('admin',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('username');
            $table->text('password');
            $table->text('full_name');
            $table->text('phone_number');
            $table->text('email');
            $table->text('avatar_url');
            $table->text('last_ip');
            $table->integer('last_access_time');
            $table->text('status');
            $table->integer('updated_at');
            $table->integer('created_at');

            $table->addPrimaryKey('id');
            $table->addIndex('idx_username','username');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('admin_logs');
        Schema::create('admin_logs',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->integer('uid');
            $table->text('username');
            $table->text('title');
            $table->text('content');
            $table->text('ipaddress');
            $table->text('request_url');
            $table->text('user_agent');
            $table->integer('request_time');

            $table->addPrimaryKey('id');
            $table->addIndex('idx_uid','uid');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('admin_menu');
        Schema::create('admin_menu',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('title');
            $table->integer('pid');
            $table->text('path')->nullable();
            $table->integer('level')->nullable()->default('0');
            $table->text('icon')->nullable();
            $table->text('link_to')->nullable();
            $table->text('link_target')->nullable();
            $table->text('link_type')->nullable()->default('action');
            $table->text('active_rule')->nullable();
            $table->text('show_position')->nullable();
            $table->integer('sort_order')->nullable()->default('0');
            $table->integer('updated_at')->nullable();
            $table->integer('created_at')->nullable();

            $table->addPrimaryKey('id');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('admin_meta');
        Schema::create('admin_meta',function(TableSchema $table){
            $table->integer('meta_id')->autoIncrement();
            $table->integer('object_id');
            $table->text('meta_name');
            $table->text('meta_value');

            $table->addPrimaryKey('meta_id');
            $table->addIndex('idx_meta_name','meta_name');
            $table->addIndex('idx_object_id','object_id');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('admin_roles');
        Schema::create('admin_roles',function(TableSchema $table){
            $table->integer('admin_id');
            $table->integer('role_id');
            $table->integer('assignment_time')->nullable();

            $table->addPrimaryKey(['admin_id', 'role_id']);

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('catalog');
        Schema::create('catalog',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('slug')->nullable();
            $table->text('title')->nullable();
            $table->text('content')->nullable();
            $table->integer('pid')->nullable();
            $table->text('path')->nullable();
            $table->integer('level')->nullable()->default('0');
            $table->integer('sort_order')->nullable()->default('0');
            $table->text('icon')->nullable();
            $table->text('thumb_url')->nullable();
            $table->text('link_to')->nullable();
            $table->text('link_type')->nullable();
            $table->integer('link_object')->nullable();
            $table->text('link_target')->nullable();
            $table->text('show_position')->nullable();
            $table->text('node_type')->nullable();
            $table->integer('created_at')->nullable();

            $table->addPrimaryKey('id');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('comments');
        Schema::create('comments',function(TableSchema $table){
            $table->integer('comment_id')->autoIncrement();
            $table->integer('node_id');
            $table->text('title');
            $table->text('author')->nullable();
            $table->text('author_email')->nullable();
            $table->text('author_url')->nullable();
            $table->text('author_ip')->nullable();
            $table->text('content');
            $table->integer('approved')->nullable()->default('0');
            $table->text('agent');
            $table->integer('parent')->nullable();
            $table->integer('created_at')->nullable();

            $table->addPrimaryKey('comment_id');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('node');
        Schema::create('node',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->integer('author_id');
            $table->text('node_type')->nullable();
            $table->text('title');
            $table->text('slug')->nullable();
            $table->text('excerpt')->nullable();
            $table->text('content')->nullable();
            $table->text('keywords')->nullable();
            $table->text('description')->nullable();
            $table->text('image')->nullable();
            $table->integer('hits')->nullable()->default('0');
            $table->integer('sort_order')->nullable()->default('0');
            $table->text('comment_status')->nullable();
            $table->integer('comment_count')->nullable()->default('0');
            $table->text('mime_type')->nullable();
            $table->text('status')->nullable();
            $table->integer('pub_time')->nullable()->default('0');
            $table->integer('update_time')->nullable()->default('0');
            $table->integer('add_time')->nullable()->default('0');

            $table->addPrimaryKey('id');
            $table->addIndex('idx_node_type','node_type');
            $table->addIndex('idx_status','status');
            $table->addIndex('idx_author_id','author_id');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('node_meta');
        Schema::create('node_meta',function(TableSchema $table){
            $table->integer('meta_id')->autoIncrement();
            $table->integer('object_id');
            $table->text('meta_name');
            $table->text('meta_value');

            $table->addPrimaryKey('meta_id');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('node_relation');
        Schema::create('node_relation',function(TableSchema $table){
            $table->integer('catalog_id');
            $table->integer('node_id');
            $table->integer('level')->nullable()->default('0');

            $table->addPrimaryKey(['catalog_id', 'node_id']);

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('node_type_field');
        Schema::create('node_type_field',function(TableSchema $table){
            $table->integer('field_id')->autoIncrement();
            $table->integer('node_type_id');
            $table->text('field_name');
            $table->text('field_label');
            $table->text('field_value')->nullable();
            $table->integer('sort_order')->nullable()->default('0');
            $table->text('type')->nullable();
            $table->text('placeholder')->nullable();

            $table->addPrimaryKey('field_id');
            $table->addIndex('idx_node_type_id','node_type_id');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('node_types');
        Schema::create('node_types',function(TableSchema $table){
            $table->integer('type_id')->autoIncrement();
            $table->text('type_name');
            $table->text('title');
            $table->text('description')->nullable();
            $table->text('node_type')->nullable();
            $table->text('version')->nullable()->default('0.0.0');
            $table->integer('sort_order')->nullable()->default('0');
            $table->integer('status')->nullable()->default('1');
            $table->integer('updated_at')->nullable();
            $table->integer('created_at')->nullable();

            $table->addPrimaryKey('type_id');
            $table->addIndex('idx_type_name','type_name');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('options');
        Schema::create('options',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('option_name');
            $table->text('option_value')->nullable();
            $table->integer('sort_order')->nullable()->default('0');
            $table->integer('autoload')->nullable()->default('0');

            $table->addPrimaryKey('id');
            $table->addIndex('idx_option_name','option_name');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('permissions');
        Schema::create('permissions',function(TableSchema $table){
            $table->integer('perm_id')->autoIncrement();
            $table->text('title');
            $table->integer('pid');
            $table->text('path')->nullable();
            $table->integer('level')->nullable()->default('0');
            $table->text('perm_key')->nullable();
            $table->text('extras')->nullable();
            $table->text('description')->nullable();
            $table->integer('updated_at')->nullable();
            $table->integer('created_at')->nullable();
            $table->integer('sort_order')->default('0');

            $table->addPrimaryKey('perm_id');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('plugin');
        Schema::create('plugin',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('name');
            $table->text('title');
            $table->text('version')->nullable()->default('1.0.0');
            $table->text('author')->nullable();
            $table->text('description')->nullable();
            $table->text('homepage')->nullable();
            $table->text('package_name')->nullable();
            $table->integer('status')->nullable()->default('1');
            $table->integer('sort_order')->nullable()->default('0');
            $table->integer('installed_at')->nullable()->default('0');
            $table->integer('updated_at')->nullable()->default('0');

            $table->addPrimaryKey('id');
            $table->addIndex('idx_name','name');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('roles');
        Schema::create('roles',function(TableSchema $table){
            $table->integer('role_id')->autoIncrement();
            $table->text('name');
            $table->text('description')->nullable();
            $table->integer('status')->nullable()->default('0');
            $table->integer('updated_at')->nullable()->default('0');
            $table->integer('created_at')->nullable()->default('0');

            $table->addPrimaryKey('role_id');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('roles_permissions');
        Schema::create('roles_permissions',function(TableSchema $table){
            $table->integer('role_id');
            $table->text('perm_key');
            $table->text('extras')->nullable();
            $table->integer('assignment_time')->nullable();

            $table->addPrimaryKey(['role_id', 'perm_key']);

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('tags');
        Schema::create('tags',function(TableSchema $table){
            $table->integer('tag_id')->autoIncrement();
            $table->text('title');
            $table->text('slug');
            $table->integer('count')->nullable()->default('0');

            $table->addPrimaryKey('tag_id');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::dropIfExists('update_history');
        Schema::create('update_history',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('target');
            $table->text('from_version');
            $table->text('to_version');
            $table->text('changelog')->nullable();
            $table->text('status')->nullable()->default('success');
            $table->integer('created_at')->nullable()->default('0');

            $table->addPrimaryKey('id');
            $table->addIndex('idx_target','target');

            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });
    }

    public function installBaseData()
    {
        CreateBaseData::install();
    }

    public function installDemoData()
    {
        
    }
}
