<?php
/*
 * Auto-generated by: php console zap:UpdateBaseData -e
 * Generated at: 2026-08-07 19:15:34
 *
 * Table structure for ALL database tables.
 * To regenerate: php console zap:UpdateBaseData -e
 */

namespace zap\cms;

use zap\db\Schema;
use zap\db\TableSchema;

class CreateTables
{
    public function createSchema()
    {

        Schema::create('admin',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('username');
            $table->text('password');
            $table->text('full_name');
            $table->text('phone_number');
            $table->text('email');
            $table->text('avatar_url');
            $table->text('last_ip');
            $table->integer('last_access_time');
            $table->text('status');
            $table->integer('updated_at');
            $table->integer('created_at');

            $table->addPrimary('admin_pk','id');
            $table->addUnique('username_index','username');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('admin_logs',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->integer('uid');
            $table->text('username');
            $table->text('title');
            $table->text('content');
            $table->text('ipaddress');
            $table->text('request_url');
            $table->text('user_agent');
            $table->integer('request_time');

            $table->addPrimary('admin_logs_pk','id');
            $table->addIndex('zap_admin_logs_uid_index','uid');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('admin_menu',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('title');
            $table->integer('pid');
            $table->text('path')->nullable();
            $table->integer('level')->nullable()->default('0');
            $table->text('icon')->nullable();
            $table->text('link_to')->nullable();
            $table->text('link_target')->nullable();
            $table->text('link_type')->nullable()->default('action');
            $table->text('active_rule')->nullable();
            $table->text('show_position')->nullable();
            $table->integer('sort_order')->nullable()->default('0');
            $table->integer('updated_at')->nullable();
            $table->integer('created_at')->nullable();

            $table->addPrimary('admin_menu_pk','id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('admin_meta',function(TableSchema $table){
            $table->integer('meta_id')->autoIncrement();
            $table->integer('object_id');
            $table->text('meta_name');
            $table->text('meta_value');

            $table->addPrimary('admin_meta_pk','meta_id');
            $table->addIndex('zap_admin_meta_meta_name_index','meta_name');
            $table->addIndex('zap_admin_meta_object_id_index','object_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('admin_roles',function(TableSchema $table){
            $table->integer('admin_id')->autoIncrement();
            $table->integer('role_id')->autoIncrement();
            $table->integer('assignment_time')->nullable();

            $table->addPrimary('admin_roles_pk','admin_id', 'role_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('catalog',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('slug')->nullable();
            $table->text('title')->nullable();
            $table->text('content')->nullable();
            $table->integer('pid')->nullable();
            $table->text('path')->nullable();
            $table->integer('level')->nullable()->default('0');
            $table->integer('sort_order')->nullable()->default('0');
            $table->text('icon')->nullable();
            $table->text('thumb_url')->nullable();
            $table->text('link_to')->nullable();
            $table->text('link_type')->nullable();
            $table->integer('link_object')->nullable();
            $table->text('link_target')->nullable();
            $table->text('show_position')->nullable();
            $table->text('node_type')->nullable();
            $table->integer('created_at')->nullable();

            $table->addPrimary('catalog_pk','id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('comments',function(TableSchema $table){
            $table->integer('comment_id')->autoIncrement();
            $table->integer('node_id');
            $table->text('title');
            $table->text('author')->nullable();
            $table->text('author_email')->nullable();
            $table->text('author_url')->nullable();
            $table->text('author_ip')->nullable();
            $table->text('content');
            $table->integer('approved')->nullable()->default('0');
            $table->text('agent');
            $table->integer('parent')->nullable();
            $table->integer('created_at')->nullable();

            $table->addPrimary('comments_pk','comment_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('node',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->integer('author_id');
            $table->text('node_type')->nullable();
            $table->text('title');
            $table->text('slug')->nullable();
            $table->text('excerpt')->nullable();
            $table->text('content')->nullable();
            $table->text('keywords')->nullable();
            $table->text('description')->nullable();
            $table->text('image')->nullable();
            $table->integer('hits')->nullable()->default('0');
            $table->integer('sort_order')->nullable()->default('0');
            $table->text('comment_status')->nullable();
            $table->integer('comment_count')->nullable()->default('0');
            $table->text('mime_type')->nullable();
            $table->text('status')->nullable();
            $table->integer('pub_time')->nullable()->default('0');
            $table->integer('update_time')->nullable()->default('0');
            $table->integer('add_time')->nullable()->default('0');

            $table->addPrimary('node_pk','id');
            $table->addIndex('zap_node_node_type_index','node_type');
            $table->addIndex('zap_node_status_index','status');
            $table->addIndex('zap_node_author_id_index','author_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('node_meta',function(TableSchema $table){
            $table->integer('meta_id')->autoIncrement();
            $table->integer('object_id');
            $table->text('meta_name');
            $table->text('meta_value');

            $table->addPrimary('node_meta_pk','meta_id');
            $table->addIndex('zap_node_meta_meta_name_index','meta_name');
            $table->addIndex('zap_node_meta_object_id_index','object_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('node_relation',function(TableSchema $table){
            $table->integer('catalog_id')->autoIncrement();
            $table->integer('node_id')->autoIncrement();
            $table->integer('level')->nullable()->default('0');

            $table->addPrimary('node_relation_pk','catalog_id', 'node_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('node_type_field',function(TableSchema $table){
            $table->integer('field_id')->autoIncrement();
            $table->integer('node_type_id');
            $table->text('field_name');
            $table->text('field_label');
            $table->text('field_value')->nullable();
            $table->integer('sort_order')->nullable()->default('0');
            $table->text('type')->nullable();
            $table->text('placeholder')->nullable();

            $table->addPrimary('node_type_field_pk','field_id');
            $table->addIndex('zap_node_type_field_node_type_id_index','node_type_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('node_types',function(TableSchema $table){
            $table->integer('type_id')->autoIncrement();
            $table->text('type_name');
            $table->text('title');
            $table->text('description')->nullable();
            $table->text('node_type')->nullable();
            $table->text('version')->nullable()->default('0.0.0');
            $table->integer('sort_order')->nullable()->default('0');
            $table->integer('status')->nullable()->default('1');
            $table->integer('updated_at')->nullable();
            $table->integer('created_at')->nullable();

            $table->addPrimary('node_types_pk','type_id');
            $table->addIndex('zap_node_types_type_name_index','type_name');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('options',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('option_name');
            $table->text('option_value')->nullable();
            $table->integer('sort_order')->nullable()->default('0');
            $table->integer('autoload')->nullable()->default('0');

            $table->addPrimary('options_pk','id');
            $table->addUnique('option_name_index','option_name');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('permissions',function(TableSchema $table){
            $table->integer('perm_id')->autoIncrement();
            $table->text('title');
            $table->integer('pid');
            $table->text('path')->nullable();
            $table->integer('level')->nullable()->default('0');
            $table->text('perm_key')->nullable();
            $table->text('extras')->nullable();
            $table->text('description')->nullable();
            $table->integer('updated_at')->nullable();
            $table->integer('created_at')->nullable();

            $table->addPrimary('permissions_pk','perm_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('permissions_path',function(TableSchema $table){
            $table->integer('perm_id')->autoIncrement();
            $table->integer('path_id')->autoIncrement();
            $table->integer('level')->nullable();

            $table->addPrimary('permissions_path_pk','perm_id', 'path_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('plugin',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('name');
            $table->text('title');
            $table->text('version')->nullable()->default('1.0.0');
            $table->text('author')->nullable();
            $table->text('description')->nullable();
            $table->text('homepage')->nullable();
            $table->text('package_name')->nullable();
            $table->integer('status')->nullable()->default('1');
            $table->integer('sort_order')->nullable()->default('0');
            $table->integer('installed_at')->nullable()->default('0');
            $table->integer('updated_at')->nullable()->default('0');

            $table->addPrimary('plugin_pk','id');
            $table->addUnique('plugin_name_uk_index','name');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('roles',function(TableSchema $table){
            $table->integer('role_id')->autoIncrement();
            $table->text('name');
            $table->text('description')->nullable();
            $table->integer('status')->nullable()->default('0');
            $table->integer('updated_at')->nullable()->default('0');
            $table->integer('created_at')->nullable()->default('0');

            $table->addPrimary('roles_pk','role_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('roles_permissions',function(TableSchema $table){
            $table->integer('role_id')->autoIncrement();
            $table->text('perm_key');
            $table->text('extras')->nullable();
            $table->integer('assignment_time')->nullable();

            $table->addPrimary('roles_permissions_pk','role_id', 'perm_key');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('tags',function(TableSchema $table){
            $table->integer('tag_id')->autoIncrement();
            $table->text('title');
            $table->text('slug');
            $table->integer('count')->nullable()->default('0');

            $table->addPrimary('tags_pk','tag_id');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });

        Schema::create('update_history',function(TableSchema $table){
            $table->integer('id')->autoIncrement();
            $table->text('target');
            $table->text('from_version');
            $table->text('to_version');
            $table->text('changelog')->nullable();
            $table->text('status')->nullable()->default('success');
            $table->integer('created_at')->nullable()->default('0');

            $table->addPrimary('update_history_pk','id');
            $table->addIndex('zap_update_history_target_idx_index','target');

            $table->dropTableIfExists();
            $table->setTableEngine(TableSchema::ENGINE_INNODB);
        });
    }

    public function installBaseData()
    {
        CreateBaseData::install();
    }

    public function installDemoData()
    {
        
    }
}
