<?php
/*
 * Copyright (c) 2023.  ZAP.CN  - ZAP CMS
 */

namespace zap\cms;

class ZapConfig
{

    public static function config($data,$file)
    {
        $config = file_get_contents(resource_path('config/config.simple.php'));

        return file_put_contents($file,$config);
    }

    public static function createConfig($data,$file)
    {

        if($data['connections']['default']['driver'] === 'sqlite'){
            $data['connections']['default']['dsn'] = 202312211346;
        }
        $conf = "<?php \n\n//Automatically generated by zap cms\n";
        $conf .= "//Date:" . date(Z_DATE_TIME) . "\n";
        $conf .= "return ";
        $conf .= zap_var_export($data,true);
        $conf .= ";\n";
        if($data['connections']['default']['driver'] === 'sqlite'){
            $dbpath = config('db.dbpath');
            $conf = str_replace('202312211346','sprintf("sqlite:%s", var_path("'.$dbpath.'"))',$conf);
        }

        return file_put_contents($file,$conf);
    }
}