<?php
/*
 * Copyright (c) 2023.  ZAP.CN  - ZAP CMS
 */

namespace zap\cms;

class ZapConfig
{

    public static function createConfig($data,$file)
    {
        $conf = "<?php \n\n//Automatically generated by zap cms\n";
        $conf .= "//Date:" . date(Z_DATE_TIME) . "\n";
        $conf .= "return ";
        $conf .= zap_var_export($data,true);
        $conf .= ";\n";
        return file_put_contents($file,$conf);
    }
}